version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-krnl_onboarding}
      POSTGRES_USER: ${POSTGRES_USER:-krnl_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-krnl_pass}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-krnl_user} -d ${POSTGRES_DB:-krnl_onboarding}"]
      interval: 3s
      timeout: 3s
      retries: 20

  api:
    build: ./backend
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app

volumes:
  pgdata:
